name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: tars2go
        run: |
          cd tars/tools/tars2go
          go mod download
          go build ./...
          go test ./...

      - name: tarsgo
        run: |
          cd tars/tools/tarsgo
          go mod tidy
          go build ./...
          go test ./...

      - name: Build
        run: |
          go mod download
          go build ./tars

      - name: Examples
        run: |
          cd _examples
          go build ./...
          go test ./...

      - name: Lint
        run: |
          go vet -stdmethods=false $(go list ./...)
          go install mvdan.cc/gofumpt@latest
          test -z "$(gofumpt -s -l -extra .)" || echo "Please run 'gofumpt -l -w -extra .'"

      - name: Codecov
        uses: codecov/codecov-action@v2
